location = /home-assistant-fix { return 301 /home-assistant-fix/; }
location /home-assistant-fix/ {
	if ($http_x_authentik_groups !~ "(^|[|])tool-home-assistant-fix([|]|$)") { return 403; }
	try_files $uri $uri/ =404;
}
