# NPM -> Proxy Host -> Tab "Advanced" -> hier einfügen.
# ERSETZEN: AUTHENTIK_IP:9000 durch Adresse deines Authentik-Servers (Port 9000 = Embedded Outpost),
# z.B. http://192.168.1.20:9000  oder  http://authentik-server:9000 (wenn gleiches Docker-Netz)

proxy_buffers 8 16k;
proxy_buffer_size 32k;
port_in_redirect off;

location /outpost.goauthentik.io {
	proxy_pass          http://AUTHENTIK_IP:9000/outpost.goauthentik.io;
	proxy_set_header    Host $host;
	proxy_set_header    X-Original-URL $scheme://$http_host$request_uri;
	add_header          Set-Cookie $auth_cookie;
	auth_request_set    $auth_cookie $upstream_http_set_cookie;
	proxy_pass_request_body off;
	proxy_set_header    Content-Length "";
}

location @goauthentik_proxy_signin {
	internal;
	add_header Set-Cookie $auth_cookie;
	return 302 /outpost.goauthentik.io/start?rd=$scheme://$http_host$request_uri;
}
